import styled from '@emotion/styled';
import Head from 'next/head';
import Image from 'next/image';
import sample from '../public/sample.png';

const Container = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
`;

export default function Index() {
  return (
    <Container>
      <Head>
        <title>Hyper Visual Report</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>
        Hyper Visual Report
      </h1>
      <Image src={sample} height="300" />
    </Container>
  );
}
